/**
 * This is an autogenerated file and can be deleted if is not in use.
 */

import { expect } from '@wdio/globals'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {

        await login('tomsmith', 'SuperSecretPassword!')
        await expect('User is logged in').toBeExisting()
    })
})

